name: GNews

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */2 * * *'  ## at minute 30 past every 2nd hour

jobs:
  gnews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Downloading the news
        uses: ./.github/actions
        with:
          url: 'https://gnews.io/api/v4/search?q=a&token=${{ secrets.API_GNEWS }}'
          news_key: 'articles'
